name: nbhzvn.one auto deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip repository
        run: |
          zip -r site.zip . -x ".git/*" ".github/*" "deploy.php"

      - name: Upload zip to server
        env:
          DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          curl -X POST "$DEPLOYMENT_URL" \
            -H "Authorization: Bearer $DEPLOYMENT_TOKEN" \
            -F "file=@site.zip"
